### ISSUE TITLE
Any Plans for Vienna Ruby Meetups in 2023? Ready-To-Help Out & Restart

### ISSUE THREAD

**Issue by geraldb** [vienna-rb/vienna-rb.github.com#102]
Hello, Ruby Vienna Meetup Orgs (& Friends). 
cc:  @abangratz @alextacho @alicetragedy @aried3r @beanieboi @cypher @FloorD @klappradla @kmikael @pxlpnk @hola-soy-milk
cc:  @gettalong @nilsding
 
  Prosit 2023! Any news or updates? I (Gerald Bauer) am happy to help out or take over and organize a series of new ruby meetups in 2023. Let me know what are your plans for 2023. Cheers. Prost. 

PS: If you prefer by email - use gerald.bauer@gmail.com or github see https://github.com/viennarb/viennarb.github.io/issues

PPS:    Anyone still using ruby?  Or are you still around in Vienna / Austria?   I invite you to share a little update on your ruby story  ( did you switch to  elixir / typescript / ____ /  etc  or changed your carreer? Are you a rich no-coder venture capitalist now? Please tell / share.

PPPS:   And the message posted to the (other / alternate) Vienna Ruby Github Org (see https://github.com/viennarb/viennarb.github.io/issues/3 )

> Let's Organize a Ruby Meetup in Vienna, Austria in 2023! Join Us. Yes, You Can.
>
> Hello,  let's organize a ruby meetup in vienna in 2023.   If you are interested, say hello or +1 or such.  Yes, you can. 
>
> - Interested in hosting the meetup / event, please tell!  Yes, you can!
> - Interested in speaking at the meetup / event, please tell! Yes, you can!
> -  Interested in sponsoring drinks or such, please tell! Yes, you can!
> - Interested in hiring ruby devs or such, please tell!  Yes, you can!   
>

**Comment by hola-soy-milk** [comment]
Thanks for checking! Watch this space as well as the viennarb Twitter and slack accounts for stuff coming real soon!

**Comment by geraldb** [comment]
Let's discuss this out in the open - the ruby community is supposed to be a community -  unfortunately my experience is that you ironically (as a fan of inclusive welcome coduct of conducts etc) treat the meetup as your personal property and closed (private) club  -  I got kicked out as you know (as a co-org) without notice, for example,  I don't really care  but I was't the first - the "other" ruby meetup org was shown the door too and so on.  I see a pattern.  Anyways,  not really expecting any change.   With ruby being past its glory and meetup org working being a thankless job it is sad to see that you cannot see past your own self-interest and open-up the org.  Cheers. Prosit 2023!

**Comment by hola-soy-milk** [comment]
Oh dear. My apologies, Gerald. I did not want to mislead you at all!

We're currently in the process of sourcing speakers and a venue for our first meetup of the year. Always thankful for and open to feedback.

**Comment by hola-soy-milk** [comment]
Just to clarify, this is an open sourcing of resources, on public spaces. 

As far as organisation goes, this is meant to be a community, and I don't want to make anyone feel excluded from voicing concerns.

**Comment by geraldb** [comment]
So who is the royal we if you care  to expand?  How do you get into the inner circle?  If you kick-out and exlude long-standing rubyists - than all you do is respond is you are always thankful for and open to feedback? What does that mean?  Sorry, I don't get it / understand or maybe if I dare to say ironically as a meetup autocrat you don't see the problem?

**Comment by mraaroncruz** [comment]
@geraldb "we" is Ramon and I who run the meetup group.
I'm speaking for myself here.

When you were a co-organizer you spammed the group with crypto meetups that confused the members so I removed you as co-organizer.

Now years later you come at us with this energy. I don't have the time or energy to deal with this.

But you're welcome to attend any meetups. Just please don't act like this if you come.

I'm not open to feedback from you. Please don't @ me again.

**Comment by geraldb** [comment]
That's my point you  Aarron Cruz and Ramón Huidobro treat the meetup as your property (and private club)  even though the heritage was good (or dare I say excellent) governance by Floor et al.   What a shame that it has come to this.   It is no joy to speak-up and call you out but this is now going on for years.

**Comment by hola-soy-milk** [comment]
you’re absolutely right, Gerald. The meetup is nowhere nearly as vibrant as it was before, and that’s on me. 

The fact that I made you feel you have to call me out is a failure in my side. I have to and will do better.

To that point, let’s kick off 2023 by bringing that energy back. Ideas for venues and talks as always are appreciated.

**Comment by geraldb** [comment]
It's not on you.  The point is about good governance.  And you two  Aarron Cruz and Ramón Huidobro are running the "show" for way to long as an exclusive circle and to repeat treat the meetup as your own property you have to bring in new people to the org team but obviously that's again the self-promotion of Aaaron who is the worst offender - your "welcoming atmosphere" spiel is just a farce if I dare to say. Ten more years!  Go Team Aaron and Ramon.   Are you even programming in ruby anymore?  See the point?

**Comment by hola-soy-milk** [comment]
Gerald, I agree. I never want to make you feel like this is my meetup and that no one has a say. 

I joined the team many years ago when the organisers started off the meetup with a call for additional organisers.

How about we do this again? You're right, it's long overdue.

**Comment by gettalong** [comment]
First I wanna say thank you to @hola-soy-milk and @mraaroncruz for organizing the Ruby meetups! And naturally to @FloorD and all the others to doing it before them!

Taking time out of one's own spare time to keeping such a meetup alive is certainly no easy task. You need to find a space to do the meetups and speakers who will speak at them. Back in the heyday of Rails' popularity it was certainly easier, especially during the "sektor5 time" because one of those things - the space - was fixed. Later in became harder and it showed but that's just how it is when there is more PL competition and people move on.

Personally, I don't have a problem even if Ramon and Aaron were to treat the meetup as "their own". So what? Like with open source projects everyone can say what they like but the maintainers (or organizers here) don't have to listen. They are not paid by anyone to do the job, they are doing it anyways and certainly have their reasons. If some of those reasons have a commercial background, so be it. If the community attending the meetups doesn't like it, they will shun the meetups and the organizers would have to change things. So its kinda self-regulatory.

I have talked at a few of the vienna.rb meetups and though some talks were more general, most were very specific to my own interests. However, if they weren't helpful to others, future talk proposals probably wouldn't be accepted.

Last thing I wanna add: From my experience Ruby is "hot" again, especially now due to the 3.2 release with YJIT being production ready and Shopify very loudly speaking out about it :grin: Don't really know about Rails 7 but from what I gather it is also kinda "hot" again.

**Comment by geraldb** [comment]
> I joined the team many years ago when the organisers started off the meetup with a call for additional organisers.
>
> How about we do this again? You're right, it's long overdue.

Sure enough that's the good governance  to ask for help and call for additional organizers.  Since it hasn't worked out with my humble self I might be a your usual "double speak".   I wish you all the best.

If you remember the desaster of the trivial task of updating and bringing back the website right here that I tried for years actually  with showing up month after month and doing what you ask for I doubt it will work out, anyways let's try again.    I open up a new ticket titled "Any Plans for the vienna.rb github org and the broken (dead) ruby vienna meetup website in 2023?" see <https://github.com/vienna-rb/vienna-rb.github.com/issues/103> .  It's up to you.

**Comment by geraldb** [comment]
> Personally, I don't have a problem even if Ramon and Aaron were to treat the meetup as "their own". So what? 

@gettalong   Sure a dictatorship works if you get out what you want.   No work on your part and you can attend great (local) meetups. Win-Win.      

But the reality is that Aaron no longer has a stake in ruby and Ramon can sure tell us more what's his plan for 2023?     Thus, prepare yourself waiting for godot.  As the smoking gun proof number one look right at this org here or the state-of-the-website.

**Comment by gettalong** [comment]
@geraldb Even if you call it dictatorship, you are free to do as you want, e.g. by not attending events, unlike in a real dictatorship.

I wouldn't say "freeloading" but I attended the meetups without contributing to many of them. However, I think this is the case for most of the people attending a meetup, being this particular one or others.

**Comment by geraldb** [comment]
Usually in a "real" verein in Austria you have a Vereinsgesetz and the members  year by year vote in the officials. The point is to have some sort of governance model / rules for a healthy community.  Anyways, as you point out even you - as the model rubyist - declaring that you have no interest in a local ruby community let's close the case.    If anyone is interested in (drop-in) ruby meetups I try one more series in 2023, see <https://viennarb.github.io/>.

**Comment by gettalong** [comment]
I'm not in a position, time- or energy-wise, to build a local ruby community, besides the fact that I would probably be the false person to do such a thing in the first place  :man_shrugging: 

Ramon, on the other hand, is a people-person and if he has the time and energy... let's help him where we can!

**Comment by geraldb** [comment]
Again for a healthy community you need good governance.  

> I'm not in a position, time- or energy-wise, to [help]... let's help him where we can!

Let's start a drumming for Ramon circle ;-).

**Comment by hola-soy-milk** [comment]
Hey all! To catch us up:

I meant what I said: I want this to be a healthy, happy community. Circumstances over the last three years have exacerbated this meetup going into a lull. I am earnestly thankful for all of your support to keep it going. This is the right time, in my opinion, to start fresh and seek additional help.

Gerald: I dropped the ball when I was starting out in the org and didn't assertively push for the new website to be published. I know words don't say much, but your work has not gone unappreciated there and I fondly remember our sessions at Ruby Habits going over these, so I'd like to make this right. 

I am well aware of the adage: Intent does not matter when it comes to impact. Therefore, I'm eager to make things right.

I'm happy to say that I might already have 2 speakers lined up for our next meetup, so that's a start.

I am, as always, thankful for the kindness and patience everyone shows me.

**Comment by geraldb** [comment]
Actually I am not asking much:

1) A Good Governance Model    - Yes, END the dictatorship and FUCK YOU declarations by Aaron Cruz etc.
2) Let's Update & Bring Back The Website (GitHub Org)  -  since nobody is left standing - let's start over at <https://github.com/viennarb> and transfer the repos here to save the heritage and close down the duplicate not in operation anyway.

**Comment by hola-soy-milk** [comment]
Gerald, I'm not going to beat around the bush: We (Aaron and I) do not feel safe transferring Github organisations. His reasons can be extrapolated from his answer above, but mine are twofold:

1. `viennarb` does not have a code of conduct. [I am well aware of how you feel about these](https://github.com/chooseaconduct/chooseaconduct.github.io#q-whats-the-point-thats-the-whole-code-three-words-wheres-the-enforcement-procedure-and-process) and will not sit here to try and convince you otherwise, but nevertheless: This meetup has long stood with one, even before I started attending, and I do not want to end this. This might be an unreasonable point of contention on my end from your point of view, and I respect that, but I do not see myself budging on this. I need to be firm on this, and I hope you understand.
2. Leadership was trusted to us when the time came. I still take responisiblity for the website. However, what happened with the merging of ruby crypto and ruby meetups that Aaron mentioned came from a difference in opinion of what the meetup should be.

I am not a solicitor, I am not Austrian, and I do not have a verein (association, for those who like me are not native German speakers), so please forgive me for not being fully aware of its said Gesetze (laws). That said, to repeat my previous point: **We will to start our next meetup with a clear, pointed call for additional leadership.**

Once we confirm a venue, which Aaron is very kindly working on, we will start the date setting and subsequent announcements.

Vienna.rb is the first meetup I ever joined and it holds a special place in my heart, the latter of which I'm sure applies to a lot of you. I understand that the frustrations are there, and I take responsibility for them.

If I may end on a more joyful note: I am super excited to hear that there is excitement building around Ruby once again as Thomas said, around YJIT. I myself streamed about Ruby and its WebAssembly support for work last year, and could bring some insight into this!

**Comment by mraaroncruz** [comment]
I didn't read this but from skimming over it, it looks like a lot of ranting and nobody needs this in their inbox anymore.

If you've ever met @hola-soy-milk, you'd know that he is being genuine here and just wants what's best for the community.

Like in the other recently closed issues, let's not waste our time fighting about something that might not exist anymore (the Vienna Ruby Community) and see if there is any spark of interest left in it.

If there is, we can discuss how to move forward. We should know by Q3 this year.
