### ISSUE TITLE
ruby.wien - This site can’t be reached

### ISSUE THREAD

**Issue by geraldb** [vienna-rb/vienna-rb.github.com#104]
Hello,

cc @aaroncm  @hola-soy-milk 

  Sorry for reporting but the advertised official link, that is, ruby.wien  is not working anymore and my humble browser says: This site can’t be reached.

 What's your take? Is it supposed to work? Thanks. Happy new year. Prosit 2023!

**Comment by hola-soy-milk** [comment]
Thanks for catching this, Gerald!

This is from a while ago. If I remember correctly, we were splitting the cost of the domain, which turned out to be pricey.

Given that this has gone unnoticed for a while, I would be happy to let it default to, say, vienna-rb.github.io, or something. What do we think?

**Comment by geraldb** [comment]
As you know I run <https://viennarb.github.io> (no dash) and if you google vienna ruby meetup or such I comes up great  - so sure <https://vienna-rb.github.io> will work great too  - and saves you money for a website that isn't in operation anyway if I dare to say.  Just my two (unasked for)  cents.

**Comment by mraaroncruz** [comment]
See https://github.com/vienna-rb/vienna-rb.github.com/issues/103
Same conclusion.
